### ISSUE TITLE
build fail for sh4 spark

### ISSUE THREAD

**Issue by woooow1** [OpenVisionE2/openvision-oe#44]
ERROR: openssl-1.0.2n-r0 do_package_write_ipk: Function failed: do_package_ipk
ERROR: Logfile of failure stored in: /home/home/openpli-oe-core/build/tmp/work/sh4-oe-linux/openssl/1.0.2n-r0/temp/log.do_package_write_ipk.9976

[log.do_package_write_ipk.txt](https://github.com/OpenVisionE2/openvision-oe/files/2775702/log.do_package_write_ipk.txt)

**Comment by woooow1** [comment]
this is not serious at all, to close ticket without any explanation!!!

**Comment by persianpros** [comment]
There is no problem in sh4 builds and you could download ready images from https://openvision.tech/stb-images/

If you're doing something wrong don't blame us.

**Comment by Hains** [comment]
Don't use cleanup.sh for a machine if you want to build for that machine again.
cleanup.sh is for cleanup unused machines only.
Delete /build/tmp dir to fix build error.

**Comment by woooow1** [comment]
Thanks @Hains for explanation!!! I will do that!

**Comment by Shadowman94** [comment]
something wentwrong about building spark image again, it seems the problem is stlirc package:

`/mnt/developement/openpli-oe-core/build/tmp/work/spark-oe-linux/stlirc/0.9.0-r0/temp/run.do_install.7052: line 133: [: missing `]'
install: cannot stat '/mnt/developement/openpli-oe-core/build/tmp/work/spark-oe-linux/stlirc/0.9.0-r0/lircd_sh4.init': No such file or directory
WARNING: /mnt/developement/openpli-oe-core/build/tmp/work/spark-oe-linux/stlirc/0.9.0-r0/temp/run.do_install.7052:1 exit 1 from 'install /mnt/developement/openpli-oe-core/build/tmp/work/spark-oe-linux/stlirc/0.9.0-r0/lircd_sh4.init /mnt/developement/openpli-oe-core/build/tmp/work/spark-oe-linux/stlirc/0.9.0-r0/image/etc/init.d/lircd'
ERROR: Function failed: do_install (log file is located at /mnt/developement/openpli-oe-core/build/tmp/work/spark-oe-linux/stlirc/0.9.0-r0/temp/log.do_install.7052)
`
Any suggesstion to fix that?

**Comment by persianpros** [comment]
I can't access pastebin, please post it here ...
